#!/usr/bin/env bash
# Regenerate tests/models/*/refs/<solver>.mat using native OMC. Runs
# inside docker/Dockerfile.native-omc (which has the matching upstream
# OpenModelica SHA built as a real binary in /opt/omc-native/bin/omc).
#
# Idempotent: re-running just overwrites the .mat files.
#
# Usage (inside Docker):  bash tests/regen-references.sh
# Usage (outside Docker): make regen-references
set -euo pipefail

OMC="${OMC:-/opt/omc-native/bin/omc}"
SOLVERS="${SOLVERS:-euler rungekutta dassl cvode ida}"

if [ ! -x "$OMC" ]; then
  echo "ERR: native omc not found at $OMC" >&2
  echo "     Run inside docker/Dockerfile.native-omc, or override OMC=…" >&2
  exit 1
fi

cd "$(dirname "$0")"

for dir in models/*/; do
  name=$(basename "$dir")
  mo="$dir/model.mo"
  [ -f "$mo" ] || continue
  mkdir -p "$dir/refs"
  for solver in $SOLVERS; do
    echo "[ref] $name :: $solver"
    out="$dir/refs/${solver}.mat"
    (cd "$dir" && \
      "$OMC" --simCodeTarget=C \
             +s --matchingAlgorithm=BFSB \
             -d=initialization \
             "$(basename "$mo")" > /dev/null) || true
    # The OMC `simulate(MODEL, simflags={"-s=$solver"})` API call is the
    # canonical way; the above only generates C. Add the actual run step
    # once we have the full native build wired.
    echo "  (placeholder — native sim run not yet implemented)"
  done
done

# Update reference-manifest.json with current OpenModelica SHA.
sha=$(git -C "$(dirname "$0")/../upstream/OpenModelica" rev-parse HEAD)
python3 -c "
import json, sys, pathlib
p = pathlib.Path('reference-manifest.json')
m = json.loads(p.read_text())
m['OpenModelica_sha'] = '$sha'
m['_status'] = 'regenerated by tests/regen-references.sh'
p.write_text(json.dumps(m, indent=2) + '\n')
"
echo "[ref] manifest updated to $sha"
