#!/usr/bin/env bash
# Writes demo-app/version.js with the version derived from git:
#   - tag name when HEAD is exactly on a tag
#   - short commit SHA otherwise
#   - "+dirty" appended if the working tree has uncommitted changes
#
# Run this before serving / shipping. serve.sh + the GitHub Pages workflow
# both call it.
set -euo pipefail
cd "$(dirname "$0")"

if VERSION=$(git describe --tags --exact-match 2>/dev/null); then
  :
elif VERSION=$(git rev-parse --short=12 HEAD 2>/dev/null); then
  :
else
  VERSION="unknown"
fi

# Treat any line returned by `git status --porcelain` as "dirty" — same
# definition the user sees in their own `git status`.
if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
  VERSION="${VERSION}+dirty"
fi

COMMIT=$(git rev-parse --short=12 HEAD 2>/dev/null || echo "unknown")
BUILT_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)

# Emit safe JS string literals via python's json.dumps — handles any odd
# chars in tag names without hand-rolling escapes.
python3 - <<PY > version.js
import json
print("// auto-generated by demo-app/gen-version.sh — do not edit.")
print("window.__OMC_VERSION  =", json.dumps("${VERSION}") + ";")
print("window.__OMC_COMMIT   =", json.dumps("${COMMIT}") + ";")
print("window.__OMC_BUILT_AT =", json.dumps("${BUILT_AT}") + ";")
PY

echo "wrote demo-app/version.js: ${VERSION} @ ${COMMIT}"
