#!/usr/bin/env bash
# Writes web/version.js with the version derived from git:
#   - tag name when HEAD is exactly on a tag
#   - short commit SHA otherwise
#   - "+dirty" appended if the working tree has uncommitted changes (tracked
#     files only; submodule state changes count as dirty too)
#
# Run this before serving / shipping the web app. serve.sh calls it for you.
set -euo pipefail
cd "$(dirname "$0")/.."

if VERSION=$(git describe --tags --exact-match 2>/dev/null); then
  :
elif VERSION=$(git rev-parse --short=12 HEAD 2>/dev/null); then
  :
else
  VERSION="unknown"
fi

# `git diff --quiet HEAD` returns non-zero when tracked files differ from HEAD.
# `git status --porcelain` also catches submodule-state changes & is what the
# user sees when they `git status`. Use that as the canonical "dirty" check.
if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
  VERSION="${VERSION}+dirty"
fi

COMMIT=$(git rev-parse --short=12 HEAD 2>/dev/null || echo "unknown")
BUILT_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)

# Emit safe JS string literals via python's json.dumps — handles any odd chars
# in tag names without us hand-rolling escapes.
python3 - <<PY > web/version.js
import json
print("// auto-generated by re-poc/scripts/gen-version.sh — do not edit.")
print("window.__OMC_VERSION  =", json.dumps("${VERSION}") + ";")
print("window.__OMC_COMMIT   =", json.dumps("${COMMIT}") + ";")
print("window.__OMC_BUILT_AT =", json.dumps("${BUILT_AT}") + ";")
PY

echo "wrote web/version.js: ${VERSION} @ ${COMMIT}"
